<a href="https://colab.research.google.com/github/aswathypkarun/DataScience-Lab/blob/main/Aswathy_06_01_2022_Na%C3%AFve_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: Program to implement Naïve Bayes Algorithm using any standard dataset
available in the public domain and find the accuracy of the algorithm


Short notes: Naive Bayes

Bayes’ Theorem provides a way that we can calculate the probability of a piece of data belonging to a given class, given our prior knowledge. Bayes’ Theorem is stated as:

P(class|data) = (P(data|class) * P(class)) / P(data)

Where P(class|data) is the probability of class given the provided data.

We are using Iris Dataset. The Iris Flower Dataset involves predicting the flower species given measurements of iris flowers.

It is a multiclass classification problem. The number of observations for each class is balanced. There are 150 observations with 4 input variables and 1 output variable. The variable names are as follows:

Sepal length in cm.

Sepal width in cm.

Petal length in cm.

Petal width in cm., and

Class.

Algorithm:

Step 1: Separate By Class.

Step 2: Summarize Dataset.

Step 3: Summarize Data By Class.

Step 4: Gaussian Probability Density Function.

Step 5: Class Probabilities.

In [ ]:
#Import Modules
import numpy as np
import pandas as pd
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
#Load iris dataset & do train_test_split 
iris=datasets.load_iris()
X=iris.data[ : , : ]
y=iris.target
Xtrain,Xtest,y_train,y_test=train_test_split(X,y,stratify=y,random_state=42,test_size=0.33)

In [ ]:
#Feature Scaling
scaler=preprocessing.StandardScaler().fit(Xtrain)
Xtrain=scaler.transform(Xtrain)
Xtest=scaler.transform(Xtest)
Xtrain

array([[ 4.89131136e-01,  7.14932910e-01,  1.03425476e+00,
         1.55502776e+00],
       [-9.18440479e-01,  9.34237484e-01, -1.33168750e+00,
        -1.16400496e+00],
       [-9.73570367e-02, -8.20199106e-01,  7.52594964e-01,
         9.07639020e-01],
       [-8.01142844e-01, -8.20199106e-01,  7.66114634e-02,
         2.60250275e-01],
       [-1.50492865e+00,  7.14932910e-01, -1.33168750e+00,
        -1.16400496e+00],
       [-8.01142844e-01,  2.25006493e+00, -1.27535554e+00,
        -1.42296046e+00],
       [-2.14654671e-01,  2.90797865e+00, -1.27535554e+00,
        -1.03452721e+00],
       [ 6.06428771e-01,  5.70191892e-02,  9.77922797e-01,
         7.78161271e-01],
       [-1.27033338e+00,  5.70191892e-02, -1.21902358e+00,
        -1.29348271e+00],
       [-1.15303575e+00,  5.70191892e-02, -1.27535554e+00,
        -1.29348271e+00],
       [ 7.23726405e-01, -6.00894532e-01,  4.70935172e-01,
         3.89728024e-01],
       [-1.15303575e+00,  5.70191892e-02, -1.27535554e+00,
      

In this step, we introduce the class GaussianNB that is used from the sklearn.naive_bayes library. Here, we have used a Gaussian model, there are several other models such as Bernoulli, Categorical and Multinomial. Here, we assign the GaussianNB class to the variable classifier and fit the X_train and y_train values to it for training purpose.

In [ ]:
#Implement Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
scores=[]
classifier=GaussianNB()
classifier.fit(Xtrain,y_train)

GaussianNB()

In [ ]:
#Predict the values for test data  
y_pred=classifier.predict(Xtest)
# Display accuracy score & display confusion matrix & classification report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print("\nConfusion Matrix\n-----------------\n",cm)
print()
print(classification_report(y_test,y_pred))

0.92

Confusion Matrix
-----------------
 [[16  0  0]
 [ 0 16  1]
 [ 0  3 14]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.84      0.94      0.89        17
           2       0.93      0.82      0.87        17

    accuracy                           0.92        50
   macro avg       0.93      0.92      0.92        50
weighted avg       0.92      0.92      0.92        50



In [ ]:
from sklearn.naive_bayes import BernoulliNB
scores=[]
classifier1=BernoulliNB()
classifier1.fit(Xtrain,y_train)
y_pred=classifier1.predict(Xtest)
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print("\nConfusion Matrix\n-----------------\n",cm)
print()
print(classification_report(y_test,y_pred))

0.82

Confusion Matrix
-----------------
 [[16  0  0]
 [ 2  9  6]
 [ 0  1 16]]

              precision    recall  f1-score   support

           0       0.89      1.00      0.94        16
           1       0.90      0.53      0.67        17
           2       0.73      0.94      0.82        17

    accuracy                           0.82        50
   macro avg       0.84      0.82      0.81        50
weighted avg       0.84      0.82      0.81        50



From the above confusion matrix, we infer that, out of 45 test set data, 44 were correctly classified and only 1 was incorrectly classified. This gives us a high accuracy of 97.7%.