<a href="https://colab.research.google.com/github/aswathypkarun/DataScience-Lab/blob/main/ASWATHY_30_11_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x=np.matrix('1 2 3;4 5 6;7 8 9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x=np.matrix([[8,7],[3,5]])
x

matrix([[8, 7],
        [3, 5]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
x=np.matrix('8 7;3 -5')
y=np.matrix('3;2')
a=np.matmul(x,y)
a

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
import numpy as np
id_matrix=np.identity(5,dtype=int)
id_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
same_matrix=np.matrix('1 2 3;4 5 6;7 8 9')
id_matrix=np.identity(3,dtype=float)
matmult=np.matmul(same_matrix,id_matrix)
matmult

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
mat_a=np.matrix('1 3 3;1 4 3;1 3 4')
inv_a=np.matrix('7 -3 -3;-1 1 0;-1 0 1')
new=np.matmul(mat_a,inv_a)
new

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x=np.matrix('8 7;3 -5')
det_x=np.linalg.det(x)
det_x

-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
x=np.matrix('1 3 3;1 4 3;1 3 4')
det_x=np.linalg.det(x)
det_x

1.0

In [ ]:
# Calculate the inverse of the above matrix A.
mat_a=np.linalg.inv(x)
mat_a

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [ ]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
import pandas as pd
weather={'date':['11/10/19','12/10/19','13/10/19','14/10/19','15/10/19'],
         'city':['Trivandrum','Kochi','Kollam','Kottayam','Kolenchery'],
         'temp':['31','32','31','33','27'],
         'windspeed':[44,55,34,43,42]}
df=pd.DataFrame(weather)
# Display the first five rows of dataframe
df.head()

#Display the last five rows of dataframe
df.tail()


date        city temp  windspeed
0  11/10/19  Trivandrum   31         44
1  12/10/19       Kochi   32         55
2  13/10/19      Kollam   31         34
3  14/10/19    Kottayam   33         43
4  15/10/19  Kolenchery   27         42